// Auto-generated by scripts/extractor.py
// Figma frame: 79:234  首页
// Size: 375×812  (wrapper height adjusted to 759 after status bar offset 53px)
// 生成时间：通过 extractor v1.2，flatten + absolute 定位 + status bar offset
//
// 后续手工细修：调整字号微差、抽公共组件、对接路由跳转、补 VECTOR 占位

export default function Page79_234() {
  return (
    <div className="absolute inset-0 overflow-y-auto overflow-x-hidden bg-white">
      <div className="relative mx-auto" style={{ width: 375, height: 759 }}>
        {/* GROUP 79:235 文本框 */}
        <div
          className="absolute"
          style={{ left: 17.0, top: 506.0, width: 343.0, height: 147.0 }}
        />
        {/* RECTANGLE 79:236 Rectangle 89 */}
        <div
          className="absolute"
          style={{ left: 17.0, top: 506.0, width: 342.0, height: 147.0, boxShadow: '-65.0px 140.0px 43.0px rgba(0,0,0,0.010), -42.0px 90.0px 40.0px rgba(0,0,0,0.060), -23.0px 51.0px 33.0px rgba(116,116,116,0.200), -10.0px 22.0px 25.0px rgba(61,61,61,0.340)', borderRadius: 16.0 }}
        />
        {/* RECTANGLE 79:237 Rectangle 90 */}
        <div
          className="absolute"
          style={{ left: 17.0, top: 506.0, width: 342.0, height: 147.0, background: '#88a088', borderRadius: 16.0 }}
        />
        {/* RECTANGLE 79:238 Rectangle 91 */}
        <div
          className="absolute"
          style={{ left: 17.0, top: 506.0, width: 343.0, height: 126.07, background: 'rgba(142,210,186,0.400)', borderRadius: 16.0 }}
        />
        {/* RECTANGLE 79:239 首页文本框 1 */}
        <img
          src="/assets/figma/figma_img_dd65defc.webp"
          alt="首页文本框 1"
          className="absolute object-cover"
          style={{ left: 17.0, top: 506.0, width: 342.0, height: 146.0 }}
          draggable={false}
        />
        {/* GROUP 79:240 文本框 */}
        <div
          className="absolute"
          style={{ left: 110.0, top: 590.0, width: 81.76, height: 18.59 }}
        />
        {/* RECTANGLE 79:241 Rectangle 89 */}
        <div
          className="absolute"
          style={{ left: 110.0, top: 590.0, width: 81.76, height: 18.59, boxShadow: '-65.0px 140.0px 43.0px rgba(0,0,0,0.010), -42.0px 90.0px 40.0px rgba(0,0,0,0.060), -23.0px 51.0px 33.0px rgba(116,116,116,0.200), -10.0px 22.0px 25.0px rgba(61,61,61,0.340)', borderRadius: 48.0 }}
        />
        {/* RECTANGLE 79:242 Rectangle 90 */}
        <div
          className="absolute"
          style={{ left: 110.0, top: 590.0, width: 81.76, height: 18.59, background: '#88a088', borderRadius: 48.0 }}
        />
        {/* RECTANGLE 79:243 Rectangle 91 */}
        <div
          className="absolute"
          style={{ left: 110.0, top: 590.0, width: 81.76, height: 15.12, background: 'rgba(51,72,54,0.400)', borderRadius: 48.0 }}
        />
        {/* VECTOR 79:244 Vector 20 */}
        <img
          src="/assets/svg/79_244.svg"
          alt="Vector 20"
          className="absolute"
          style={{ left: 112.04, top: 603.64, width: 64.9, height: 4.96 }}
          draggable={false}
        />
        {/* VECTOR 79:245 Vector 21 */}
        <img
          src="/assets/svg/79_245.svg"
          alt="Vector 21"
          className="absolute"
          style={{ left: 112.04, top: 603.64, width: 64.9, height: 4.96 }}
          draggable={false}
        />
        {/* VECTOR 79:246 Vector 22 */}
        <img
          src="/assets/svg/79_246.svg"
          alt="Vector 22"
          className="absolute"
          style={{ left: 126.35, top: 590.25, width: 61.65, height: 4.71 }}
          draggable={false}
        />
        {/* TEXT 79:247 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 121.24, top: 587.0, width: 67.0, height: 22.0, fontSize: 15.0, color: '#ffffff', fontWeight: 400, lineHeight: '22.0px', fontFamily: 'var(--font-zh)' }}
        >
          初阶茶客
        </span>
        {/* GROUP 79:248 文本框 */}
        <div
          className="absolute"
          style={{ left: 16.0, top: 264.0, width: 343.0, height: 215.0 }}
        />
        {/* RECTANGLE 79:249 Rectangle 89 */}
        <div
          className="absolute"
          style={{ left: 16.0, top: 265.0, width: 342.99, height: 214.0, boxShadow: '-65.0px 140.0px 43.0px rgba(0,0,0,0.010), -42.0px 90.0px 40.0px rgba(0,0,0,0.060), -23.0px 51.0px 33.0px rgba(116,116,116,0.200), -10.0px 22.0px 25.0px rgba(61,61,61,0.340)', borderRadius: 16.0 }}
        />
        {/* RECTANGLE 79:250 Rectangle 90 */}
        <div
          className="absolute"
          style={{ left: 16.0, top: 265.0, width: 342.99, height: 214.0, background: '#88a088', borderRadius: 16.0 }}
        />
        {/* RECTANGLE 79:251 Rectangle 91 */}
        <div
          className="absolute"
          style={{ left: 16.0, top: 265.0, width: 343.0, height: 165.84, background: 'rgba(142,210,186,0.400)', borderRadius: 16.0 }}
        />
        {/* RECTANGLE 79:252 11e7aa9091b27396d5b775930daddbd9 1 */}
        <img
          src="/assets/figma/figma_img_cef07f43.webp"
          alt="11e7aa9091b27396d5b775930daddbd9 1"
          className="absolute object-cover"
          style={{ left: 16.0, top: 264.0, width: 343.0, height: 215.0 }}
          draggable={false}
        />
        {/* RECTANGLE 79:253 首页轮播图棕色版 1 */}
        <img
          src="/assets/figma/figma_img_885fcd3b.webp"
          alt="首页轮播图棕色版 1"
          className="absolute object-cover"
          style={{ left: 0.0, top: -9.0, width: 374.0, height: 249.0 }}
          draggable={false}
        />
        {/* GROUP 79:254 Group 29 */}
        <div
          className="absolute"
          style={{ left: 289.0, top: -2.0, width: 70.0, height: 34.0 }}
        />
        {/* RECTANGLE 79:255 Rectangle 17 */}
        <div
          className="absolute"
          style={{ left: 289.0, top: -2.0, width: 70.0, height: 34.0, background: '#fffefe', borderRadius: 16.0 }}
        />
        {/* FRAME 79:256 Frame 1 */}
        <div
          className="absolute"
          style={{ left: 296.0, top: 2.0, width: 56.0, height: 24.0 }}
        />
        {/* FRAME 79:257 More horizontal */}
        <div
          className="absolute"
          style={{ left: 296.0, top: 2.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR 79:258 Icon */}
        <img
          src="/assets/svg/79_258.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 300.0, top: 13.0, width: 16.0, height: 2.0 }}
          draggable={false}
        />
        {/* FRAME 79:259 Disc */}
        <div
          className="absolute"
          style={{ left: 328.0, top: 2.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR 79:260 Icon */}
        <img
          src="/assets/svg/79_260.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 330.0, top: 4.0, width: 20.0, height: 20.0 }}
          draggable={false}
        />
        {/* GROUP 79:261 Group 31 */}
        <div
          className="absolute"
          style={{ left: 289.0, top: -2.0, width: 70.0, height: 34.0 }}
        />
        {/* RECTANGLE 79:262 Rectangle 17 */}
        <div
          className="absolute"
          style={{ left: 289.0, top: -2.0, width: 70.0, height: 34.0, background: '#fffefe', borderRadius: 16.0 }}
        />
        {/* FRAME 79:263 Frame 1 */}
        <div
          className="absolute"
          style={{ left: 296.0, top: 2.0, width: 56.0, height: 24.0 }}
        />
        {/* FRAME 79:264 More horizontal */}
        <div
          className="absolute"
          style={{ left: 296.0, top: 2.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR 79:265 Icon */}
        <img
          src="/assets/svg/79_265.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 300.0, top: 13.0, width: 16.0, height: 2.0 }}
          draggable={false}
        />
        {/* FRAME 79:266 Disc */}
        <div
          className="absolute"
          style={{ left: 328.0, top: 2.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR 79:267 Icon */}
        <img
          src="/assets/svg/79_267.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 330.0, top: 4.0, width: 20.0, height: 20.0 }}
          draggable={false}
        />
        {/* GROUP 79:268 Group 30 */}
        <div
          className="absolute"
          style={{ left: 289.0, top: -2.0, width: 70.0, height: 34.0 }}
        />
        {/* RECTANGLE 79:269 Rectangle 17 */}
        <div
          className="absolute"
          style={{ left: 289.0, top: -2.0, width: 70.0, height: 34.0, background: '#fffefe', borderRadius: 16.0 }}
        />
        {/* FRAME 79:270 Frame 1 */}
        <div
          className="absolute"
          style={{ left: 296.0, top: 2.0, width: 56.0, height: 24.0 }}
        />
        {/* FRAME 79:271 More horizontal */}
        <div
          className="absolute"
          style={{ left: 296.0, top: 2.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR 79:272 Icon */}
        <img
          src="/assets/svg/79_272.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 300.0, top: 13.0, width: 16.0, height: 2.0 }}
          draggable={false}
        />
        {/* FRAME 79:273 Disc */}
        <div
          className="absolute"
          style={{ left: 328.0, top: 2.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR 79:274 Icon */}
        <img
          src="/assets/svg/79_274.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 330.0, top: 4.0, width: 20.0, height: 20.0 }}
          draggable={false}
        />
        {/* RECTANGLE 79:275 Rectangle 1 */}
        <div
          className="absolute"
          style={{ left: 0.0, top: -53.0, width: 375.0, height: 44.0, background: '#ffffff' }}
        />
        {/* FRAME 79:276 Frame 8 */}
        <div
          className="absolute"
          style={{ left: -10.0, top: 715.0, width: 395.0, height: 54.0 }}
        />
        {/* RECTANGLE 79:277 Rectangle 2 */}
        <div
          className="absolute"
          style={{ left: 0.0, top: 725.0, width: 375.0, height: 34.0, background: '#ffffff' }}
        />
        {/* SKIPPED chrome: 79:278 handle */}
        {/* RECTANGLE 79:279 矩形 */}
        <div
          className="absolute"
          style={{ left: 0.0, top: 675.0, width: 375.0, height: 50.0, background: '#faf8f3', boxShadow: '0.0px -1.0px 0.0px #ccb791, 0.0px -1.0px 5.0px rgba(239,213,168,0.500)', borderRadius: '16.0px 16.0px 0.0px 0.0px' }}
        />
        {/* SKIPPED chrome: 79:280 Building Blocks/navigation */}
        {/* TEXT 79:282 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 55.0, top: 286.0, width: 93.0, height: 40.0, fontSize: 32.0, color: '#4a3526', fontWeight: 700, lineHeight: '40.0px', fontFamily: 'var(--font-zh)' }}
        >
          预    约
        </span>
        {/* TEXT 79:283 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 222.0, top: 286.0, width: 93.0, height: 40.0, fontSize: 32.0, color: '#4a3526', fontWeight: 700, lineHeight: '40.0px', fontFamily: 'var(--font-zh)' }}
        >
          订    单
        </span>
        {/* TEXT 79:284 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 31.0, top: 335.0, width: 140.0, height: 28.0, fontSize: 20.0, color: '#4a3526', fontWeight: 300, lineHeight: '28.0px', fontFamily: 'var(--font-zh)' }}
        >
          提前预约免排队
        </span>
        {/* TEXT 79:285 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 200.0, top: 336.0, width: 140.0, height: 28.0, fontSize: 20.0, color: '#4a3526', fontWeight: 300, lineHeight: '28.0px', fontFamily: 'var(--font-zh)' }}
        >
          看看上次买了啥
        </span>
        {/* SKIPPED chrome: 79:286 Status bar - iPhone */}
        {/* TEXT 79:296 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 111.0, top: 563.0, width: 80.0, height: 22.0, fontSize: 15.0, color: '#6c4c35', fontWeight: 400, lineHeight: '22.0px', fontFamily: 'var(--font-zh)' }}
        >
          用户941110
        </span>
        {/* TEXT 79:297 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 234.0, top: 587.0, width: 106.0, height: 32.0, fontSize: 24.0, color: '#4a3526', fontWeight: 500, lineHeight: '32.0px', fontFamily: 'var(--font-zh)' }}
        >
          余额/充值
        </span>
        {/* TEXT 79:298 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 36.0, top: 707.0, width: 24.0, height: 16.0, fontSize: 12.0, color: '#6c4c35', fontWeight: 500, lineHeight: '16.0px', fontFamily: 'var(--font-zh)' }}
        >
          首页
        </span>
        {/* TEXT 79:299 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 300.0, top: 707.0, width: 52.0, height: 16.0, fontSize: 12.0, color: '#6c4c35', fontWeight: 500, lineHeight: '16.0px', fontFamily: 'var(--font-zh)' }}
        >
          会员中心
        </span>
        {/* TEXT 79:300 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 223.0, top: 707.0, width: 29.0, height: 16.0, fontSize: 12.0, color: '#6c4c35', fontWeight: 500, lineHeight: '16.0px', fontFamily: 'var(--font-zh)' }}
        >
          商城
        </span>
        {/* TEXT 79:301 */}
        <span
          className="absolute whitespace-pre-wrap"
          style={{ left: 132.0, top: 707.0, width: 52.0, height: 16.0, fontSize: 12.0, color: '#6c4c35', fontWeight: 400, lineHeight: '16.0px', fontFamily: 'var(--font-zh)' }}
        >
          茶文化
        </span>
        {/* GROUP 79:302 Mask group */}
        <div
          className="absolute"
          style={{ left: 31.0, top: 558.0, width: 56.0, height: 56.0 }}
        />
        {/* ELLIPSE 79:303 Ellipse 1 */}
        <div
          className="absolute"
          style={{ left: 31.0, top: 558.0, width: 56.0, height: 56.0, background: '#ffffff', borderRadius: '50%' }}
        />
        {/* RECTANGLE 79:304 image 1 */}
        <img
          src="/assets/figma/figma_img_f247170a.webp"
          alt="image 1"
          className="absolute object-cover"
          style={{ left: 31.0, top: 558.0, width: 58.0, height: 58.0 }}
          draggable={false}
        />
        {/* INSTANCE 79:305 User */}
        <div
          className="absolute"
          style={{ left: 312.0, top: 681.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR I79:305;7758:12533 Icon */}
        <img
          src="/assets/svg/I79_305-7758_12533.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 316.0, top: 684.0, width: 16.0, height: 18.0 }}
          draggable={false}
        />
        {/* INSTANCE 79:306 Shopping bag */}
        <div
          className="absolute"
          style={{ left: 223.0, top: 681.0, width: 24.0, height: 24.0 }}
        />
        {/* VECTOR I79:306;7758:12239 Icon */}
        <img
          src="/assets/svg/I79_306-7758_12239.svg"
          alt="Icon"
          className="absolute"
          style={{ left: 226.0, top: 683.0, width: 18.0, height: 20.0 }}
          draggable={false}
        />
        {/* RECTANGLE 79:307 茶文化原色图标 1 */}
        <img
          src="/assets/figma/figma_img_6a299efd.webp"
          alt="茶文化原色图标 1"
          className="absolute object-cover"
          style={{ left: 140.0, top: 678.0, width: 18.0, height: 27.0 }}
          draggable={false}
        />
        {/* RECTANGLE 79:308 余额棕色版 1 */}
        <img
          src="/assets/figma/figma_img_c7595451.webp"
          alt="余额棕色版 1"
          className="absolute object-cover"
          style={{ left: 256.0, top: 544.0, width: 60.0, height: 44.0 }}
          draggable={false}
        />
        {/* RECTANGLE 79:309 首页图标变色 1 */}
        <img
          src="/assets/figma/figma_img_a4165237.webp"
          alt="首页图标变色 1"
          className="absolute object-cover"
          style={{ left: 27.0, top: 660.0, width: 48.0, height: 55.0 }}
          draggable={false}
        />
        {/* RECTANGLE 79:310 预约图标棕色版 1 */}
        <img
          src="/assets/figma/figma_img_c065d02d.webp"
          alt="预约图标棕色版 1"
          className="absolute object-cover"
          style={{ left: 63.0, top: 389.0, width: 77.0, height: 55.0 }}
          draggable={false}
        />
        {/* GROUP 79:311 Group 1 */}
        <div
          className="absolute"
          style={{ left: 328.0, top: 223.0, width: 27.2, height: 8.23 }}
        />
        {/* ELLIPSE 79:312 Ellipse 23 */}
        <div
          className="absolute"
          style={{ left: 328.0, top: 223.0, width: 8.23, height: 8.23, background: '#ffffff', borderRadius: '50%' }}
        />
        {/* ELLIPSE 79:313 Ellipse 24 */}
        <div
          className="absolute"
          style={{ left: 340.23, top: 224.37, width: 5.49, height: 5.49, background: '#ffffff', borderRadius: '50%' }}
        />
        {/* ELLIPSE 79:314 Ellipse 25 */}
        <div
          className="absolute"
          style={{ left: 349.71, top: 224.37, width: 5.49, height: 5.49, background: '#ffffff', borderRadius: '50%' }}
        />
        {/* RECTANGLE 79:315 订单棕色版 1 */}
        <img
          src="/assets/figma/figma_img_8007fef6.webp"
          alt="订单棕色版 1"
          className="absolute object-cover"
          style={{ left: 247.0, top: 375.0, width: 46.0, height: 82.0 }}
          draggable={false}
        />
        {/* SKIPPED chrome: 79:4650 stellis_yanxing */}
      </div>
    </div>
  )
}
